import { DM_Sans } from "next/font/google";
import localFont from "next/font/local";

import NextTopLoader from "nextjs-toploader";

import { ThemeProvider } from "@mui/material";
import { Toaster } from "react-hot-toast";

import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import ChatBox from "@/components/popups/ChatBox";
import AdminLoginFAB from "@/components/popups/AdminLoginFAB";

import { AuthProvider } from "@/contexts/AuthContext";

import theme from "@/styles/mui/theme";
import "@/styles/globals.css";

const pinland = localFont({
  src: [
    {
      path: "../../public/fonts/Pinland-Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-pinland",
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} ${pinland.variable}`}>
        <AuthProvider>
          <ThemeProvider theme={theme}>
            <NextTopLoader
              color="var(--secondary)"
              initialPosition={0.08}
              crawlSpeed={200}
              height={3}
              crawl={true}
              showSpinner={false}
              easing="ease"
              speed={200}
            />
            <Header />
            <main>{children}</main>
            <Footer />
            <AdminLoginFAB />
            <ChatBox />
            <Toaster
              position="top-center"
              reverseOrder={false}
              toastOptions={{
                style: {
                  borderRadius: "var(--low-rounded)",
                  background: "var(--grey-1)",
                  color: "var(--white)",
                },
              }}
            />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
