import { DM_Sans } from "next/font/google";

import { ThemeProvider } from "@mui/material";

import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

import theme from "@/styles/mui/theme";
import "@/styles/globals.css";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable}`}>
        <ThemeProvider theme={theme}>
          <Header />
          <main>{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
